version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: ["sh", "-c", "python manage.py migrate && python manage.py seed_content && python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p 8000 app.asgi:application"]

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    command: ["celery", "-A", "app", "worker", "-l", "info"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
