# Generated by Django 5.2.5 on 2025-08-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='action',
            field=models.CharField(choices=[('viewed', 'Viewed'), ('liked', 'Liked'), ('disliked', 'Disliked'), ('completed', 'Completed')], max_length=50),
        ),
    ]
