# Generated by Django 5.2.5 on 2025-08-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_interaction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommendations',
            field=models.JSONField(blank=True, default=list, help_text='Stored recommendations from collaborative filtering'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='action',
            field=models.CharField(max_length=50),
        ),
    ]
