# Generated by Django 5.2.5 on 2025-08-20 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_recommendations_alter_interaction_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ContentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0, help_text='Percentage of users who complete the content')),
                ('avg_time_spent', models.PositiveIntegerField(default=0, help_text='Average time spent in seconds')),
                ('popularity_score', models.FloatField(default=0.0)),
                ('difficulty_rating', models.FloatField(default=2.5, help_text='1-5 scale based on user completion time')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.contentitem')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=100)),
                ('score', models.FloatField(default=0.0)),
                ('served_at', models.DateTimeField(auto_now_add=True)),
                ('interacted', models.BooleanField(default=False)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='core.contentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-served_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_content_viewed', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Total time in seconds')),
                ('quizzes_attempted', models.PositiveIntegerField(default=0)),
                ('quizzes_completed', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('learning_streak', models.PositiveIntegerField(default=0, help_text='Consecutive days of activity')),
                ('topic_progress', models.JSONField(blank=True, default=dict, help_text='Progress by topic category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Content View'), ('start', 'Learning Started'), ('complete', 'Learning Completed'), ('quiz_attempt', 'Quiz Attempt'), ('quiz_complete', 'Quiz Completed'), ('search', 'Search Performed'), ('recommendation_click', 'Recommendation Clicked')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional contextual data')),
                ('content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='core.contentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='core_analyt_user_id_77c57e_idx'), models.Index(fields=['content_item', 'event_type'], name='core_analyt_content_6d7ed6_idx'), models.Index(fields=['timestamp'], name='core_analyt_timesta_768eea_idx')],
            },
        ),
    ]
